// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import ()

type Todo struct {
	ID     int32
	Text   string
	Done   bool
	UserID int32
}

type User struct {
	ID   int32
	Name string
}
